$FORT ABSORB.F
$FORT ABS.F
$FORT ATOMDATA.F
$FORT CROMER.F
$FORT CRYS_ABS.F
$FORT ELEMENT.F
$FORT GSTRING.F
$FORT MATL_ABS.F
$FORT RAYCOMP.F
$FORT RDLAT.F
$FORT SFCOEF.F
$FORT STR_FACT.F
$FORT XNRG_B_D.F
$FORT XSEC_B_D.F
$LINK ABSORB,ABS,ATOMDATA,CROMER,CRYS_ABS,ELEMENT,GSTRING,-
 MATL_ABS,RAYCOMP,RDLAT,SFCOEF,STR_FACT,XNRG_B_D,XSEC_B_D

